<?php

return array (
  'version' => '3.5.18',
  'codename' => 'Fix TypeError insertConceptDetail',
  'build' => '2026-01-15',
  'environment' => 'production',
  'last_updated' => '2026-01-15 00:00:00',
  'changelog' =>
  array (
    '3.5.18' => 'Fix TypeError insertConceptDetail',
    '3.5.17' => 'Bug Fixes + UX Improvements',
    '3.5.16' => 'Expedientes Empleados + Migraciones Multi-Tenant',
    '3.5.15' => 'UNIDAD Dinámica en Fórmulas',
    '3.5.14' => 'Campo UNIDAD en Planilla Detalle',
    '3.5.13' => 'Sistema Permisos Granulares + Liquidaciones Dinámicas',
    '3.5.12' => 'Acumulados Excel Export + Bug Fixes',
    '3.5.6' => 'Sincronización Calendario API + Feriados Pagados + Unificación',
    '3.5.5' => 'Almuerzo en Asistencias + Proceso Unificado',
    '3.5.4' => 'Reportes Asistencias + Mejoras UI Planillas',
    '3.5.3' => 'Eliminación eval() + Arquitectura Segura',
    '3.5.2' => 'Mejora Reportes Liquidaciones',
    '3.5.1' => 'Data Cleanup & Fixes Críticos',
    '3.4.8' => 'Procesamiento Completo Día Asistencias',
    '3.4.7' => 'Integración Planillas-Asistencias',
    '3.4.6' => 'Sistema Alertas Legales',
    '3.4.5' => 'Integración UI Calculadores',
    '3.4.4' => 'AttendanceCalculator + AbsenceDetector',
    '3.4.3' => 'Vistas Separadas Asistencias',
    '3.4.2' => 'Checkbox Validación Situación',
    '3.4.1' => 'Migraciones BD Asistencias',
    '3.4.0' => 'Integración API Base44',
    '3.3.22' => 'Inicialización Automática Calendario',
    '3.3.21' => 'Calendario Empresarial Panamá',
    '3.2.1' => 'Motor Fórmulas Conceptos Optimizado V2',
    '3.2.0' => 'Módulo Organizacional + Logos Empresariales',
    '3.1.0' => 'Sistema Acumulados + JavaScript Modular',
    '3.0.0' => 'Acumulados Panamá + Sistema Empresarial',
  ),
);
